In [1]:
import numpy as np

In [11]:
arr_2d = np.arange(25)

In [12]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr_2d.dtype

dtype('int32')

In [14]:
arr_2d.shape

(25,)

In [35]:
new = arr_2d.reshape(5,5)

0

In [36]:
new.shape

(5, 5)

In [37]:
new

array([[ 0,  1, 22, 22, 22],
       [ 5,  6, 22, 22, 22],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
new[2,2]

12

In [46]:
new[:2,2:] = [3,4,5],[7,8,9]

In [41]:
new

array([[ 0,  1,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
new[:2, 2:] = 22

In [47]:
new

array([[ 0,  1,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr_n = new[new>14]

In [56]:
arr_n

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr_n.shape

(10,)

In [62]:
arr_2dn = arr_n.reshape(5,2)

In [65]:
arr_2dn.shape

(5, 2)

In [66]:
arr_2dn

array([[15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [67]:
bool_arr = arr_2dn > 20

In [69]:
fals_bool_arr = bool_arr == False

In [70]:
fals_bool_arr

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [False, False]])

In [71]:
bool_arr

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [72]:
new_array = np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [76]:
new_new_array = [new_array > 20]

In [78]:
new_new_array

[array([[False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]])]

In [80]:
array = np.arange(11)

In [81]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
con_selc = array[array>4]

In [89]:
con_selc

array([ 5,  6,  7,  8,  9, 10])

In [92]:
reshaped = con_selc.reshape(2,3)

In [91]:
con_selc

array([ 5,  6,  7,  8,  9, 10])

In [93]:
reshaped

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [95]:
copy = reshaped.copy()

In [96]:
copy

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [98]:
copy.dtype

dtype('int32')

In [100]:
copy.shape

(2, 3)